// AUTOMATICALLY GENERATED BY wordarrays ANALYZER.
#include "StdAfx.h"
_TCHAR *word2[]={0,
_T("aa"),_T("ab"),_T("ad"),_T("ae"),_T("ag"),_T("ah"),_T("ai"),_T("al"),_T("am"),_T("an"),
_T("ar"),_T("as"),_T("at"),_T("aw"),_T("ax"),_T("ay"),_T("ba"),_T("be"),_T("bi"),_T("bo"),
_T("by"),_T("da"),_T("de"),_T("do"),_T("ed"),_T("ef"),_T("eh"),_T("el"),_T("em"),_T("en"),
_T("er"),_T("es"),_T("et"),_T("ex"),_T("fa"),_T("go"),_T("ha"),_T("he"),_T("hi"),_T("hm"),
_T("ho"),_T("id"),_T("if"),_T("in"),_T("is"),_T("it"),_T("jo"),_T("ka"),_T("la"),_T("li"),
_T("lo"),_T("ma"),_T("me"),_T("mi"),_T("mm"),_T("mo"),_T("mu"),_T("my"),_T("na"),_T("ne"),
_T("no"),_T("nu"),_T("od"),_T("oe"),_T("of"),_T("oh"),_T("om"),_T("on"),_T("op"),_T("or"),
_T("os"),_T("ow"),_T("ox"),_T("oy"),_T("pa"),_T("pe"),_T("pi"),_T("re"),_T("sh"),_T("si"),
_T("so"),_T("ta"),_T("ti"),_T("to"),_T("uh"),_T("um"),_T("un"),_T("up"),_T("us"),_T("ut"),
_T("we"),_T("wo"),_T("xi"),_T("xu"),_T("ya"),_T("ye"),_T("yo"),
0};
