/*******************************************************************************
Copyright © 1999-2009 by Text Analysis International, Inc.
All rights reserved.
********************************************************************************
*/
// AUTOMATICALLY GENERATED BY wordarrays ANALYZER.
#define MAXWORDLENGTH	30
extern WORDS_API long word_lengths[];
extern WORDS_API _TCHAR **word_arrays[];
extern _TCHAR *word1[];
extern _TCHAR *word2[];
extern _TCHAR *word3[];
extern _TCHAR *word4[];
extern _TCHAR *word5[];
extern _TCHAR *word6[];
extern _TCHAR *word7[];
extern _TCHAR *word8[];
extern _TCHAR *word9[];
extern _TCHAR *word10[];
extern _TCHAR *word11[];
extern _TCHAR *word12[];
extern _TCHAR *word13[];
extern _TCHAR *word14[];
extern _TCHAR *word15[];
extern _TCHAR *word16[];
extern _TCHAR *word17[];
extern _TCHAR *word18[];
extern _TCHAR *word19[];
extern _TCHAR *word20[];
extern _TCHAR *word21[];
extern _TCHAR *word22[];
extern _TCHAR *word23[];
extern _TCHAR *word24[];
extern _TCHAR *word25[];
extern _TCHAR *word26[];
extern _TCHAR *word27[];
extern _TCHAR *word28[];
extern _TCHAR *word29[];
extern _TCHAR *word30[];
